data_types.exe: data_types.cpp
	g++ -std=c++2a data_types.cpp -o data_types.exe
	./data_types.exe

stdio.exe: stdio.cpp
	g++ -std=c++2a stdio.cpp -o stdio.exe
	./stdio.exe

functions.exe: functions.cpp
	g++ -std=c++2a functions.cpp -o functions.exe
	./functions.exe

classes.exe: classes.cpp
	g++ -std=c++2a classes.cpp -o classes.exe
	./classes.exe

inheritance.exe: inheritance_polymorphism.cpp
	g++ -std=c++2a inheritance_polymorphism.cpp -o inheritance.exe
	./inheritance.exe

smart_pointers.exe: smart_pointers.cpp
	g++ -std=c++2a smart_pointers.cpp -o smart_pointers.exe
	./smart_pointers.exe

exception.exe: exception.cpp
	g++ exception.cpp -o exception.exe
	./exception.exe int
	./exception.exe dbl

streams.exe: streams.cpp
	g++ -std=c++2a streams.cpp -o streams.exe
	./streams.exe

standard_library.exe: standard_library.cpp
	g++ -std=c++2a standard_library.cpp -o standard_library.exe
	./standard_library.exe

clean:
	rm -f *.exe
