data_types.exe: data_types.cpp
	g++ data_types.cpp -o data_types.exe
	./data_types.exe

stdio.exe: stdio.cpp
	g++ stdio.cpp -o stdio.exe
	./stdio.exe

functions.exe: functions.cpp
	g++ functions.cpp -o functions.exe
	./functions.exe

clean:
	rm -f *.exe
